import ProgramasPic from '../../assets/programas/ProgramasPic';

const ProgramasData = [
  {
    id: 1,
    nombre: "ESPECIALIZACIÓN EN GERENCIA DE EMPRESAS AGROPECUARIAS",
    facultad: "Ciencias y Tecnologías",
    SNIES: 7475,
    modalidad: "Distancia",
    nivel: "posgrado",
    foto: ProgramasPic.empAgro,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-posgrado/especializacion-en-gerencia-de-empresas-agropecuarias",
    valor: "5.095.900",
    target: "_blank"
  },
  {
    id: 2,
    nombre: "ESPECIALIZACIÓN EN GESTIÓN PARA EL DESARROLLO EMPRESARIAL",
    facultad: "Ciencias y Tecnologías",
    SNIES: 7512,
    modalidad: "Distancia",
    nivel: "posgrado",
    foto: ProgramasPic.gestDesa,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-posgrado/especializacion-en-gestion-para-el-desarrollo-empresarial",
    valor: "5.492.700",
    target: "_blank"
  },
  {
    id: 3,
    nombre: "Especialización en Gestión Integral de Cuencas Hidrográficas",
    facultad: "Ciencias y Tecnologías",
    SNIES: 110770,
    modalidad: "Virtual",
    nivel: "posgrado",
    foto: ProgramasPic.espCuencas,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-posgrado/especializacion-en-ordenamientos-y-gestion-integral-de-cuencas-hidrograficas",
    valor: "5.095.900",
    target: "_blank"
  },
  {
    id: 4,
    nombre: "ESPECIALIZACIÓN EN PATOLOGÍA DE LA CONSTRUCCIÓN",
    facultad: "Ciencias y Tecnologías",
    SNIES: 7510,
    modalidad: "Distancia",
    nivel: "posgrado",
    foto: ProgramasPic.espPato,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-posgrado/especializacion-en-patologia-de-la-construccion",
    valor: "5.492.700",
    target: "_blank"
  },
  {
    id: 7,
    nombre: "MAESTRÍA EN GESTIÓN DE CUENCAS HIDROGRAFICAS",
    facultad: "Ciencias y Tecnologías",
    SNIES: 105491,
    modalidad: "Distancia",
    nivel: "posgrado",
    foto: ProgramasPic.maesCuencas,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-posgrado/maestria-en-gestion-de-cuencas-hidrograficas",
    valor: "7.611.200",
    target: "_blank"
  },
  {
    id: 13,
    nombre: "DOCTORADO EN EDUCACIÓN",
    facultad: "Educación",
    SNIES: 90328,
    modalidad: "Presencial",
    nivel: "posgrado",
    foto: ProgramasPic.doctEdu,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-posgrado/doctorado-en-educacion",
    valor: "12.267.500",
    target: "_blank"
  },
  {
    id: 14,
    nombre: "ESPECIALIZACIÓN EN PEDAGOGÍA PARA LA EDUCACIÓN SUPERIOR",
    facultad: "Educación",
    SNIES: 54884,
    modalidad: "Distancia",
    nivel: "posgrado",
    foto: ProgramasPic.espPedag,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-posgrado/especializacion-en-pedagogia-para-la-educacion-superior",
    valor: "5.095.900",
    target: "_blank"
  },
  {
    id: 21,
    nombre: "Maestría en Ambientes Bilingües de Aprendizaje",
    facultad: "Educación",
    SNIES: 105393,
    modalidad: "Distancia",
    nivel: "Virtual",
    foto: ProgramasPic.maBa,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/presentacion-programa-maba",
    valor: "4.200.000",
    target: "_blank"
  },
  {
    id: 22,
    nombre: "MAESTRÍA EN DIDÁCTICA",
    facultad: "Educación",
    SNIES: 19996,
    modalidad: "Distancia",
    nivel: "posgrado",
    foto: ProgramasPic.maesDidac,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-posgrado/maestria-en-didactica",
    valor: "7.611.200",
    target: "_blank"
  },
  {
    id: 23,
    nombre: "MAESTRÍA EN EDUCACIÓN",
    facultad: "Educación",
    SNIES: 106755,
    modalidad: "Distancia",
    nivel: "posgrado",
    foto: ProgramasPic.maesEdu,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-posgrado/maestria-en-educacion",
    valor: "7.611.200",
    target: "_blank"
  },
  {
    id: 24,
    nombre: "MAESTRÌA EN GESTIÒN Y EVALUACIÓN EDUCATIVA",
    facultad: "Educación",
    SNIES: 110266,
    modalidad: "posgrado",
    nivel: "posgrado",
    foto: ProgramasPic.maesGestion,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-posgrado/maestria-en-gestion-y-evaluacion-educativa",
    valor: "7.611.200",
    target: "_blank"
  },
  {
    id: 25,
    nombre: "Especialización en Defensa Derechos Humanos",
    facultad: "Derecho",
    SNIES: 110695,
    modalidad: "Virtual",
    nivel: "posgrado",
    foto: ProgramasPic.maesDerecho,
    link: "https://facultadderecho.usta.edu.co/index.php/nuestros-programas/especializacion-en-defensa-de-los-derechos-humanos-virtual",
    valor: "3.900.000",
    target: "_blank"
  },
  {
    id: 5,
    nombre: "INGENIERÍA EN INFORMÁTICA",
    facultad: "Ciencias y Tecnologías",
    SNIES: 52595,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.ingeInfo,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-pregrado/ingenieria-en-informatica",
    valor: 491,
    target: "_blank"
  },
  {
    id: 6,
    nombre: "INGENIERÍA EN LOGÍSTICA Y OPERACIONES",
    facultad: "Ciencias y Tecnologías",
    SNIES: 105774,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.logOper,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-pregrado/ingenieria-en-logistica-y-operaciones",
    valor: 452.9,
    target: "_blank"
  },
  {
    id: 8,
    nombre: "ZOOTÉCNIA",
    facultad: "Ciencias y Tecnologías",
    SNIES: 53097,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.zooTec,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-pregrado/zootecnia",
    valor: 452.9,
    target: "_blank"
  },
  {
    id: 9,
    nombre: "ADMINISTRACIÓN AMBIENTAL Y DE LOS RECURSOS NATURALES",
    facultad: "Ciencias y Tecnologías",
    SNIES: 4674,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.admonAmb,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-pregrado/administracion-ambiental-y-de-los-recursos-naturales",
    valor: 452.9,
    target: "_blank"
  },
  {
    id: 10,
    nombre: "ADMINISTRACIÓN DE EMPRESAS",
    facultad: "Ciencias y Tecnologías",
    SNIES: 1082,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.admonEmp,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-pregrado/administracion-de-empresas",
    valor: 452.9,
    target: "_blank"
  },
  {
    id: 12,
    nombre: "CONSTRUCCIÓN EN ARQUITECTURA E INGENIERÍA",
    facultad: "Ciencias y Tecnologías",
    SNIES: 4400,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.constArq,
    link: "http://facultadcienciastecnologias.ustadistancia.edu.co/index.php/programas-de-pregrado/construccion-en-arquitectura-e-ingenieria",
    valor: 491,
    target: "_blank"
  },
  {
    id: 15,
    nombre: "LICENCIATURA EN BIOLOGÍA",
    facultad: "Educación",
    SNIES: 105858,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.licBio,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-pregrado/licenciatura-en-biologia",
    valor: 498.5,
    target: "_blank"
  },
  {
    id: 16,
    nombre: "LICENCIATURA EN ARTES PLÁSTICAS",
    facultad: "Educación",
    SNIES: 105856,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.licArtes,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-pregrado/licenciatura-en-artes-plasticas",
    valor: 498.5,
    target: "_blank"
  },
  {
    id: 17,
    nombre: "LICENCIATURA EN EDUCACIÓN INFANTIL",
    facultad: "Educación",
    SNIES: 105776,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.licInfan,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-pregrado/licenciatura-en-educacion-infantil",
    valor: 452.9,
    target: "_blank"
  },
  {
    id: 18,
    nombre: "LICENCIATURA EN EDUCACIÓN RELIGIOSA",
    facultad: "Educación",
    SNIES: 106034,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.licRelig,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-pregrado/licenciatura-en-educacion-religiosa",
    valor: 465.6,
    target: "_blank"
  },
  {
    id: 19,
    nombre: "LICENCIATURA EN LENGUAS EXTRANJERAS INGLÉS",
    facultad: "Educación",
    SNIES: 51648,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.licIng,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-pregrado/licenciatura-en-lenguas-extranjeras-ingles",
    valor: 500.6,
    target: "_blank"
  },
  {
    id: 20,
    nombre: "LICENCIATURA EN TEOLOGÍA",
    facultad: "Educación",
    SNIES: 54059,
    modalidad: "Distancia",
    nivel: "profesionales",
    foto: ProgramasPic.licTeolog,
    link: "http://facultadeducacion.ustadistancia.edu.co/index.php/programas-de-pregrado/licenciatura-en-teologia",
    valor: 500.6,
    target: "_blank"
  }
]

export default ProgramasData;